### ISSUE TITLE
Input element for submit form

### ISSUE THREAD

**Issue by shacorne** [dry-blessing/mgt656-spring-2015-project#15]
I can click a input element to submit the event. This element should have id="submit" and type="submit".

**Comment by shacorne** [comment]
Karen - has this been completed and tested?

**Comment by Karencillare** [comment]
No, I'm working on it. I chose it as my activity for Sprint 4.

Is that fine? It is because I started working on it.

Karen

On Nov 8, 2015, at 10:19 PM, shacorne <notifications@github.com<mailto:notifications@github.com>> wrote:


Karen - has this been completed and tested?

**Comment by shacorne** [comment]
Sure! Wanted to check as it was the "in progress" column :)

**Comment by Karencillare** [comment]
Sorry about that! I've just changed its place 😊

Sent from my iPhone

On Nov 8, 2015, at 10:26 PM, shacorne <notifications@github.com<mailto:notifications@github.com>> wrote:


Sure! Wanted to check as it was the "in progress" column :)
