### ISSUE TITLE
Look and feel of events on the homepage

### ISSUE THREAD

**Issue by shacorne** [dry-blessing/mgt656-spring-2015-project#9]
As a user, I should be able to look at the title, date and location of the events on the homepage.

**Comment by sarriaga** [comment]
That is complete but I still believe that the style should be better. I'll do it

**Comment by shacorne** [comment]
@sarriaga In addition to making it look good, please ensure the following mocha tests pass (currently they are failing). Look up file test.js and the project page for details on how to make them pass - you need to enter the ID of the element.
 The home page
     1) should have a list of events
     2) should have a time tag for each event (@karencillare had done this task in previous sprint but I think she has to mention the ID to make the test pass)
     3) should have a link for each event
